on:
  schedule:
    - cron:  '* 8 * * *' # 08:00 UTC
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - uses: actions/checkout@v3
        with:
          ref: github-pages
